//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VSPowerToys.ResourceRefactor.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VSPowerToys.ResourceRefactor.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cs.
        /// </summary>
        internal static string ExtensionCSharp {
            get {
                return ResourceManager.GetString("ExtensionCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vb.
        /// </summary>
        internal static string ExtensionVB {
            get {
                return ResourceManager.GetString("ExtensionVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract resource.
        /// </summary>
        internal static string ExtractResourceUndoContextName {
            get {
                return ResourceManager.GetString("ExtractResourceUndoContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource name.
        /// </summary>
        internal static string InvalidResourceName {
            get {
                return ResourceManager.GetString("InvalidResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file is not supported.
        /// </summary>
        internal static string ProjectFileInvalid {
            get {
                return ResourceManager.GetString("ProjectFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (/\*([^*]|(\*(^/)))*\*/)|(//[^\n]*).
        /// </summary>
        internal static string RegexCSharpComments {
            get {
                return ResourceManager.GetString("RegexCSharpComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;([^\&quot;\\\n]|\\&apos;|\\0|\\a|\\b|\\f|\\r|\\v|\\&quot;|\\n|\\t|\\\\)*&quot;)|(@&quot;([^\&quot;]|(\&quot;\&quot;))*&quot;).
        /// </summary>
        internal static string RegexCSharpLiteral {
            get {
                return ResourceManager.GetString("RegexCSharpLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   (?&lt;=&lt;((?&lt;tag&gt;\w+)((\s+\w+(\s*=\s*(?:&quot;.*?&quot;|&apos;.*?&apos;|[^&apos;&quot;&gt;\s]+))?)+\s*|\s*))&gt;)([^&lt;&quot;]*)(?=&lt;/\s*\&lt;tag&gt;\s*&gt;).
        ///   (?<=<((?<tag>\w+)((\s+\w+(\s*=\s*(?:".*?"|'.*?'|[^'">\s]+))?)+\s*|\s*))>)([^<"]*)(?=</\s*\<tag>\s*>)
        /// </summary>
        internal static string RegexInnerXML {
            get {
                return ResourceManager.GetString("RegexInnerXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;|(REM))[^\n]*.
        /// </summary>
        internal static string RegexVBComments {
            get {
                return ResourceManager.GetString("RegexVBComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;([^\&quot;]|(\&quot;\&quot;))*&quot;.
        /// </summary>
        internal static string RegexVBLiteral {
            get {
                return ResourceManager.GetString("RegexVBLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&lt;!--([^-]|(-[^-])--\&gt;.
        /// </summary>
        internal static string RegexXamlComments {
            get {
                return ResourceManager.GetString("RegexXamlComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;[^&quot;]*&quot;)|(&apos;[^&apos;]+&apos;).
        /// </summary>
        internal static string RegexXamlLiteral {
            get {
                return ResourceManager.GetString("RegexXamlLiteral", resourceCulture);
            }
        }
    }
}
