//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VSPowerToys.ResourceRefactor.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VSPowerToys.ResourceRefactor.UnitTests.TestStrings", typeof(TestStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             test = Resource1.Test;.
        /// </summary>
        internal static string CSharpReplaceTestExpectedLine {
            get {
                return ResourceManager.GetString("CSharpReplaceTestExpectedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         string test = Resources.Resource.TestResource;.
        /// </summary>
        internal static string CSharpWebsiteTestString {
            get {
                return ResourceManager.GetString("CSharpWebsiteTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a&quot;hhhh\&quot;.
        /// </summary>
        internal static string InvalidTestString {
            get {
                return ResourceManager.GetString("InvalidTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a&quot;hhhhh\.
        /// </summary>
        internal static string InvalidTestVBString {
            get {
                return ResourceManager.GetString("InvalidTestVBString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      string test = &quot;Simple Test String&quot;;.
        /// </summary>
        internal static string SimpleTestString {
            get {
                return ResourceManager.GetString("SimpleTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t = &quot;0\t1\&quot;\\\n3n&quot;.
        /// </summary>
        internal static string SpecialCharacterTestString {
            get {
                return ResourceManager.GetString("SpecialCharacterTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         test = My.Resources.Resource1.Test.
        /// </summary>
        internal static string VBReplaceTestExpectedLine {
            get {
                return ResourceManager.GetString("VBReplaceTestExpectedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Dim s As String = Resources.Resource.TestResource.
        /// </summary>
        internal static string VBWebsiteTestString {
            get {
                return ResourceManager.GetString("VBWebsiteTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t=@&quot;\&quot;&quot;;.
        /// </summary>
        internal static string VerbatimInvalidTestString {
            get {
                return ResourceManager.GetString("VerbatimInvalidTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t=@&quot;1234&quot;
        ///&quot;5678&quot;;.
        /// </summary>
        internal static string VerbatimMultiLineTestInvalidString {
            get {
                return ResourceManager.GetString("VerbatimMultiLineTestInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t=@&quot;1234
        ///5678&quot;;.
        /// </summary>
        internal static string VerbatimMultiLineTestString {
            get {
                return ResourceManager.GetString("VerbatimMultiLineTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t=@&quot;a&quot;&quot;b&quot;;.
        /// </summary>
        internal static string VerbatimQuoteTestString {
            get {
                return ResourceManager.GetString("VerbatimQuoteTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t=@&quot;VerbatimString\&quot;;.
        /// </summary>
        internal static string VerbatimTestString {
            get {
                return ResourceManager.GetString("VerbatimTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         string t = Resources.Global.Test;.
        /// </summary>
        internal static string WebApplicationGlobalTestStringCSharp {
            get {
                return ResourceManager.GetString("WebApplicationGlobalTestStringCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Dim t As String = Resources.Global.Test.
        /// </summary>
        internal static string WebApplicationGlobalTestStringVB {
            get {
                return ResourceManager.GetString("WebApplicationGlobalTestStringVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         string t = LocalResource.Test;.
        /// </summary>
        internal static string WebApplicationLocalTestStringCSharp {
            get {
                return ResourceManager.GetString("WebApplicationLocalTestStringCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Dim t As String = My.Resources.LocalResource.Test.
        /// </summary>
        internal static string WebApplicationLocalTestStringVB {
            get {
                return ResourceManager.GetString("WebApplicationLocalTestStringVB", resourceCulture);
            }
        }
    }
}
